### PR TITLE
Fix ghost clicks on chapter and stream select

### LINKED ISSUE #3: Ghost taps in video player UI
When an animation is going on, apparently compose only transforms or alters the pixels of the drawn elements. It does not change the hit boxes. Therefore, you can tap on elements that are visually not there anymore or are visually at a different location.

## You can find this at different places but here is an example to reproduce:
1. Play a video and go to fullscreen mode
2. Open the chapters screen
3. Close the chapter screen
4. Immediately after closing tap somewhere in the middle of the screen. (The hiding animation of the chapters select screen must still go on).

## What happens:
To the eye it looks like the chapter select screen is not visible anymore. However, by quickly taping in the middle of the screen while the chapter select screen hiding animation is still going on you were still able to select a different chapter.

## What should happen:
The mentioned behavior is irritating. Since NewPipe is WISWIG.
You can not see the select screen. Instead, you can see either the blank video or the video controller UI.
Because of this either the video controller or the touch ui should get the input. Not the hiding chapter UI.

Keep in mind that this issue is just an example. You can find a similar behavior when the video controller UI hides or when the playlist select screen hides.

### PR DESCRIPTION
**Pull request by lm41**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

This PR fixes ghost clicks (#3) on the chapter select box. The same logic can be applied to the stream select UI but I couldn't find a way to test the stream select UI so I left it out for now.

#### Fixes the following issue(s)
- Fixes #3

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShareASmile** [comment]
Thanks for the PR. Keep them coming. 

Next time please use "Fixes" keyword followed by Issue no. in your PR description to automatically link and close an associated issue when the pull request is merged.

If a previously unreported bug is found in the NewPlayer, please don't hesitate to create a new issue about that first. Thank you.

**Comment by lm41** [comment]
I didn't use the `fixes` keyword because this PR only partially fixes the problem. (Only in the chapter select but not in the stream select UI).
I'll have to check if I can use the same approach there as well.

**Comment by ShareASmile** [comment]
Okay, so this is WIP, btw you can use "partially fixes" or "may fix" prefixes if that's the case.

File: new-player/src/main/java/net/newpipe/newplayer/ui/selection_ui/StreamSelectUI.kt [hunk 1]
```diff
@@ -120,7 +120,13 @@ internal fun ReorderableStreamItemsList(
             ) { isDragging ->
                 StreamItem(
                     playlistItem = playlistItem,
-                    onClicked = { viewModel.streamSelected(index) },
+                    onClicked = {
+                        if (!uiState.uiMode.isStreamSelect) {
+                            // We don't select the chapter when we are not in stream select mode
```
Comment (TobiGr) [inline new-player/src/main/java/net/newpipe/newplayer/ui/selection_ui/StreamSelectUI.kt]:
```suggestion
                            // We don't select the stream when we are not in stream select mode
```

**Review by TobiGr — APPROVED** [review]
Thank you. Changes LGTM, I just have a nitpick.
I also could not find a good way to test the stream select UI for this specific case. (We really need to set up proper testing...)

File: new-player/src/main/java/net/newpipe/newplayer/ui/selection_ui/StreamSelectUI.kt (hunk 1 above)
Comment (lm41) [reply new-player/src/main/java/net/newpipe/newplayer/ui/selection_ui/StreamSelectUI.kt]: The typical copy paste mistake :-)
Fixed in the latest commit.

**Comment by lm41** [comment]
I think I found a way to test the StreamSelectUI in this specific use case:
1. Add multiple videos to the queue
2. Go to fullscreen mode
3. Click on the icon next to the three vertical dots.

The stream select UI is the queue UI. If it is not used anywhere else we should think about renaming it because stream select implies (at least for me), that multiple resolutions or audio streams can be selected with it.

**Comment by theScrabi** [comment]
I'm going to check this. :)

**Comment by theScrabi** [comment]
lgdm :)

**Review by theScrabi — APPROVED** [review]

**Comment by theScrabi** [comment]
@lm41 although this is only partly a fix, because now the tap is being ignored, which is better than before, but what I would actually expect as a user is for [GuestureUI](https://github.com/TeamNewPipe/NewPlayer/blob/dev/new-player/src/main/java/net/newpipe/newplayer/ui/videoplayer/GestureUI.kt) to react on the tap.
Can we make that work?

**Comment by Stypox** [comment]
@theScrabi I think it's fine to ignore taps while stuff is phasing in/out. However we should change the animation Easing so that it's clear when the animation is still running (something like SlowInFastOut, or even just linear).

**Comment by lm41** [comment]
@theScrabi I'm currently not at home but I'll have a look into that later next week

**Comment by lm41** [comment]
> Can we make that work?

We possibly could, but that would probably mean that we would have to intercept touch events and pass them to the GestureUI.
